server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/employees/** to employee-service
        - id: employee-service-route
          uri: http://employee-service:4000
          predicates:
            - Path=/api/employees/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/employees to employee-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://employee-service:4000
          predicates:
            - Path=/api-docs/employees
          filters:
            - RewritePath=/api-docs/employees,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
