apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4004
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service-service
spec:
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
